# -*- coding: utf-8 -*-
"""UMR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/197vkgByjK1uQFB6tUaDAPSNHt-yHBLtF
"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

!kaggle datasets download -d xhlulu/140k-real-and-fake-faces

import zipfile
zip_ref =zipfile.ZipFile('140k-real-and-fake-faces.zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

import pandas as pd

pd.read_csv('train.csv')

from PIL import Image
import matplotlib.pyplot as plt
import scipy.fftpack as fftpack

import numpy as np

df = pd.read_csv('train.csv')
base_path = "real_vs_fake/real-vs-fake/"
df['full_path'] = base_path + df['path']

print(f"Total images available: {len(df)}")

real_subset = df[df['label_str']== 'real'].sample(n=2000 , random_state=69)

fake_subset = df[df['label_str']== 'fake'].sample(n=2000 , random_state=69)

df_subset = pd.concat([real_subset,fake_subset])

df_subset = df_subset.sample(frac=1 ,random_state=69).reset_index(drop=True)

def extract_features(fr):
  feat=[]
  lab=[]
  for index,row in fr.iterrows():
    try:
      ip = row['full_path']
      with Image.open(ip) as img:
        img = img.convert('L').resize((64,64))
        img_array = np.array(img)
        f = np.fft.fft2(img_array)
        fshift = np.fft.fftshift(f)
        magnitude_spectrum = 20 * np.log(np.abs(fshift) + 1e-9)
        mean_freq = np.mean(magnitude_spectrum)
        std_freq = np.std(magnitude_spectrum)
        mean_pixel = np.mean(img_array)
        feat.append([mean_freq, std_freq, mean_pixel])
        lab.append(row['label'])
    except Exception as e:
      pass
  return np.array(feat), np.array(lab)
X, y = extract_features(df_subset)
print("-" * 30)
print("COMPLETED.")
print(f"X Shape: {X.shape}")
print(f"y Shape: {y.shape}")

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"X_train Shape: {X_train.shape}")
print(f"X_test Shape:  {X_test.shape}")
print(f"y_train Shape: {y_train.shape}")
print(f"y_test Shape:  {y_test.shape}")

from sklearn.ensemble import RandomForestClassifier

# 1. Initialize Random Forest (starts with 100 trees by default)
rf_model = RandomForestClassifier(n_estimators=100, random_state=69)

# 2. Train
rf_model.fit(X_train, y_train)

# 3. Predict
y_pred_rf = rf_model.predict(X_test)

# 4. Evaluate
print(f"RF Accuracy: {accuracy_score(y_test, y_pred_rf):.4f}")
print("\n--- RF Confusion Matrix ---")
print(confusion_matrix(y_test, y_pred_rf))

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(random_state=69)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Classification model trained.")
print(f"Sample predictions: {y_pred[:5]}")

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Calculate overall accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f} ({accuracy*100:.2f}%)")

print("\n--- Confusion Matrix ---")
print(confusion_matrix(y_test, y_pred))

print("\n--- Classification Report ---")
print(classification_report(y_test, y_pred))

import matplotlib.pyplot as plt
import seaborn as sns

# Create a temporary DataFrame for plotting
import pandas as pd
df_plot = pd.DataFrame(X_train, columns=['Feature 1', 'Feature 2', 'Feature 3'])
df_plot['Target'] = y_train

# Plot Feature 1 vs Feature 2
plt.figure(figsize=(8, 6))
sns.scatterplot(
    data=df_plot,
    x='Feature 1',
    y='Feature 2',
    hue='Target',
    palette='viridis',
    alpha=0.6
)
plt.title('Feature 1 vs Feature 2 (Colored by Class)')
plt.show()

# Create a full DataFrame with the target for visualization
df_full = pd.DataFrame(X_train, columns=['Feature 1', 'Feature 2', 'Feature 3'])
df_full['Target'] = y_train

# Use seaborn to plot every pair of features
# 'hue' colors the points by class
# 'diag_kind' shows the histogram distribution for each feature
sns.pairplot(df_full, hue='Target', palette='viridis', plot_kws={'alpha': 0.5})
plt.show()

from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# 1. Create the pipeline: Expand features -> Scale -> Classify
poly_model = Pipeline([
    ('poly', PolynomialFeatures(degree=2, include_bias=False)),
    ('scaler', StandardScaler()),
    ('classifier', LogisticRegression(random_state=42, max_iter=1000))
])

# 2. Train on the original (unscaled) split
# The pipeline handles the scaling internally
poly_model.fit(X_train, y_train)

# 3. Predict and Evaluate
y_pred_poly = poly_model.predict(X_test)

print(f"Poly Acc: {accuracy_score(y_test, y_pred_poly):.4f}")
print("\n--- Polynomial Confusion Matrix ---")
print(confusion_matrix(y_test, y_pred_poly))

import pandas as pd

# Create a DataFrame combining X and y
df_check = pd.DataFrame(X, columns=['F1', 'F2', 'F3'])
df_check['Target'] = y

# Count how many duplicate rows exist (based on features only)
duplicates = df_check.duplicated(subset=['F1', 'F2', 'F3'], keep=False)
num_duplicates = duplicates.sum()

print(f"Total rows involved in duplicates: {num_duplicates}")

if num_duplicates > 0:
    # Check for consistency: Do duplicates have DIFFERENT targets?
    # We group by features and count how many unique targets exist for each group
    inconsistent = df_check.groupby(['F1', 'F2', 'F3'])['Target'].nunique()

    # If nunique > 1, it means the same X maps to multiple different y's
    conflicts = inconsistent[inconsistent > 1]
    print(f"Number of conflicting groups (Same X, Different y): {len(conflicts)}")
else:
    print("Data is clean (no duplicates).")

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# Initialize Neural Network
# hidden_layer_sizes=(64, 32) creates a deep network with two layers
# max_iter=1000 ensures it has enough time to find the pattern
mlp_model = MLPClassifier(hidden_layer_sizes=(64, 32),
                          activation='relu',
                          solver='adam',
                          max_iter=1000,
                          random_state=42)

# Train on the SCALED data (Critical for Neural Nets)
mlp_model.fit(X_train, y_train)

# Predict
y_pred_mlp = mlp_model.predict(X_test)

print(f"Neural Net Accuracy: {accuracy_score(y_test, y_pred_mlp):.4f}")

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Create a DataFrame
df = pd.DataFrame(X, columns=['Feature 1', 'Feature 2', 'Feature 3'])
df['Target'] = y

# Calculate correlations
corr_matrix = df.corr()

# Print the correlation of each feature with the Target
print("Correlation with Target:")
print(corr_matrix['Target'].sort_values(ascending=False))

# Plot heatmap
plt.figure(figsize=(6, 5))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', vmin=-1, vmax=1)
plt.title("Correlation Matrix")
plt.show()

from sklearn.ensemble import GradientBoostingClassifier

# 1. Drop Feature 3 (Index 2) because it is noise
# We only keep Feature 1 (Index 0) and Feature 2 (Index 1)
X_train_clean = X_train[:, [0, 1]]
X_test_clean = X_test[:, [0, 1]]

# 2. Initialize Gradient Boosting
# This builds trees sequentially, trying to correct the errors of the previous tree
gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# 3. Train
gb_model.fit(X_train_clean, y_train)

# 4. Predict
y_pred_gb = gb_model.predict(X_test_clean)

print(f"Gradient Boosting Accuracy (w/o Noise): {accuracy_score(y_test, y_pred_gb):.4f}")

import matplotlib.pyplot as plt

# Plot the target variable 'y' in its original order
plt.figure(figsize=(12, 4))
plt.plot(y[:500], marker='.', linestyle='none', label='First 500 samples') # limiting to 500 to see details
plt.title("Target Variable (y) in Sequence")
plt.xlabel("Index (Time)")
plt.ylabel("Class (0 or 1)")
plt.legend()
plt.show()

df = pd.read_csv('train.csv') # or whatever your file is
print(df.columns)
print(df.head())

import os
import cv2
import numpy as np
import pandas as pd

# 1. Define the columns based on your print output
filename_col = 'path'   # The column with "train/real/31355.jpg"
label_col = 'label'     # The column with 0 or 1

# 2. Set the Base Path
# Based on your screenshot, your folder is likely '/content/real_vs_fake/real-vs-fake/'
# If the code prints "File NOT found", we will adjust this path.
base_path = '/content/real_vs_fake/real-vs-fake/'

print(f"Looking for images in: {base_path}")

# Load a subset (first 4000) for testing
df_subset = df.head(4000)

image_data = []
labels = []

print("Starting image load...")

for index, row in df_subset.iterrows():
    # Construct the full path
    # This combines "/content/.../" with "train/real/xxxxx.jpg"
    img_path = os.path.join(base_path, row[filename_col])

    # Debug print for the very first image only (to check path)
    if index == 0:
        print(f"Attempting to load first image from: {img_path}")

    # Read the image
    img = cv2.imread(img_path)

    if img is not None:
        # Resize to 256x256 (matches your target size)
        img = cv2.resize(img, (256, 256))

        # Normalize (0 to 1)
        img = img / 255.0

        image_data.append(img)
        labels.append(row[label_col])
    else:
        # If img is None, the path is wrong. Print the error for the first failure.
        if len(image_data) == 0:
             print(f"ERROR: Could not read image at {img_path}. Check your base_path!")
             break

# 3. Convert to Numpy Arrays
if len(image_data) > 0:
    X_images = np.array(image_data)
    y_labels = np.array(labels)
    print("------------------------------------------------")
    print("SUCCESS!")
    print(f"X Shape: {X_images.shape}")
    print(f"y Shape: {y_labels.shape}")
    print("You are now ready to train a CNN.")
else:
    print("No images were loaded. Please check the 'base_path' variable.")

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models, optimizers
import os

# --- CONFIGURATION ---
# 1. Path to your CSV file
csv_path = 'train.csv'

# 2. Path to the FOLDER containing the 'train' folder
# This matches the folder structure you showed in your screenshots
base_img_path = '/content/real_vs_fake/real-vs-fake/'

print(f"Checking for images in: {base_img_path}")

# --- DATA LOADING ---
# Load the CSV metadata
try:
    df = pd.read_csv(csv_path)
    print(f"Successfully loaded CSV with {len(df)} rows.")
except FileNotFoundError:
    print(f"ERROR: Could not find {csv_path}. Please make sure you uploaded it.")

# Check the first few rows to confirm column names
# We expect 'path' (relative path) and 'label' (0/1) or 'label_str' ('real'/'fake')
print("First 5 rows of data:")
print(df.head())

# --- GENERATOR SETUP (The RAM Saver) ---
# This creates a "stream" that loads images on-the-fly
train_datagen = ImageDataGenerator(
    rescale=1./255,        # Normalize pixel values (0-255 -> 0-1)
    validation_split=0.2   # Reserve 20% of data for validation
)

print("\n--- Setting up Training Stream ---")
train_generator = train_datagen.flow_from_dataframe(
    dataframe=df,
    directory=base_img_path,   # Folder where images are stored
    x_col='path',              # Column with "train/real/0000.jpg"
    y_col='label_str',         # Column with "real" or "fake" strings
    target_size=(256, 256),    # Resize images to 256x256
    batch_size=32,             # Load 32 images at a time (Low RAM usage)
    class_mode='binary',       # Real vs Fake
    subset='training',         # This is the Training set
    shuffle=True
)

print("\n--- Setting up Validation Stream ---")
val_generator = train_datagen.flow_from_dataframe(
    dataframe=df,
    directory=base_img_path,
    x_col='path',
    y_col='label_str',
    target_size=(256, 256),
    batch_size=32,
    class_mode='binary',
    subset='validation',       # This is the Validation set
    shuffle=False
)

# --- MODEL ARCHITECTURE ---
model = models.Sequential([
    # Input Layer
    layers.Input(shape=(256, 256, 3)),

    # Convolution Block 1
    layers.Conv2D(32, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Convolution Block 2
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Convolution Block 3
    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Classification Head
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),                # Helps prevent overfitting
    layers.Dense(1, activation='sigmoid') # Output: 0-1 probability
])

# Compile
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

print("Model compiled successfully!")
model.summary()

# --- TRAINING ---
print("Starting training...")
history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=5  # You can increase this to 10 or 20 later
)

print("Training complete.")

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <audio src="https://raw.githubusercontent.com/anars/blank-audio/master/10-minutes-of-silence.mp3" autoplay loop hidden id="audio"></audio>
# <script>
#     function playAudio() {
#         var audio = document.getElementById("audio");
#         audio.play();
#     }
#     // Click every 60 seconds
#     setInterval(playAudio, 60000);
# </script>

# Save the model to a single file
model.save('deepfake_detector_93acc.h5')

print("Model saved successfully as 'deepfake_detector_93acc.h5'")

import numpy as np
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

# 1. Pick a random image
test_image_path = '/content/real_vs_fake/real-vs-fake/test/fake/00276TOPP4.jpg' # Example

try:
    # 2. Load and Preprocess
    img = image.load_img(test_image_path, target_size=(256, 256))
    plt.imshow(img)
    plt.axis('off')
    plt.show()

    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array /= 255.0

    # 3. Predict
    prediction = model.predict(img_array)
    score = prediction[0][0]

    print(f"Raw Model Score: {score:.4f}")

    # --- THE FIX IS HERE ---
    # Since class_indices is {'fake': 0, 'real': 1}:
    # Score close to 0 means FAKE.
    # Score close to 1 means REAL.

    if score < 0.5:
        # Closer to 0
        print(f"🚨 RESULT: FAKE (Confidence: {(1-score)*100:.2f}%)")
    else:
        # Closer to 1
        print(f"✅ RESULT: REAL (Confidence: {score*100:.2f}%)")

except FileNotFoundError:
    print("Check your file path.")

# Check the mapping
print(train_generator.class_indices)

